/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /Users/anthonyaragues/Documents/lab/web3d/public/models/r3f_xwing2.glb -o /Users/anthonyaragues/Documents/lab/web3d/models/r3f_xwing2.js -p 3 
*/
import { useRef, useEffect } from 'react'
import * as THREE from 'three'
//import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useMotion } from '@react-three/drei'

/* NOTES

- auto set navmesh by name or custom prop, set invisible too
- onClick event highlight mesh
- wireframes are triangulated
- add bg color to setup component
- name the MESH, not just the object, maybe addon to sync them
*/

export function Model(props) {
  const { nodes, materials } = useGLTF('models/r3f_xwing2.glb');
  const poi = useRef();

  const highlight = function(mesh){
    const oldMaterial = mesh.material;
    const newMaterial = new THREE.MeshStandardMaterial({ color: 0xff0000, wireframe: true, wireframeLinewidth: 2, emissive: 0xff0000, emissiveIntensity: 5 });
    for (let i = 0; i < 4; i++) {
      setTimeout(() => { mesh.material = newMaterial; },i * 100);
      setTimeout(() => { mesh.material = oldMaterial; },i * 150);
      setTimeout(() => { mesh.material = newMaterial; },i * 200);
    }
  }

  const toggleWingRotation = function(mesh,arrRotate){
    //get the existing rotation
    const rotation = mesh.rotation;
    if(rotation.x !== arrRotate[0] && rotation.y !== arrRotate[1] && rotation.z !== arrRotate[2]) {
      mesh.rotation.x = 0;
      mesh.rotation.y = 0;
      mesh.rotation.z = 0;
    }else{
      mesh.rotation.x = arrRotate[0];
      mesh.rotation.y = arrRotate[1];
      mesh.rotation.z = arrRotate[2];
    }
  }

  useEffect(() => {
    
  }, []);

  return (
    <group dispose={null}>

      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={90.712} position={[0, -54.204, 20.242]} rotation={[1.571, 0, 0]} />
      <mesh visible={false} geometry={nodes.navmesh.geometry} material={nodes.navmesh.material} position={[0, 0, 1.97]} rotation={[Math.PI / 2, 0, 0]} scale={[173.497, 44.727, 53.942]} />
      <mesh visible={true} geometry={nodes['X-Wing_fighter'].geometry} material={materials.X_Wing_texture} ref={poi} onClick={(e)=>highlight(e.object)} />
      <mesh visible={true} geometry={nodes['X-Wing_fighter_1'].geometry} material={materials.R2D2_texture} />
      <mesh geometry={nodes.wing_bottom_left.geometry} material={materials.X_Wing_texture} onClick={(e)=>toggleWingRotation(e.object, [0,0,-0.2])}>
        <group position={[11.571, -5.539, -8.455]}>
          <mesh geometry={nodes['X-Wing_fighter009'].geometry} material={materials.X_Wing_texture} onClick={(e)=>highlight(e.object)} />
        </group>
        <mesh geometry={nodes.gun_bottom_left.geometry} material={materials.X_Wing_texture} position={[37.25, -2.696, 16.141]} onClick={(e)=>highlight(e.object)} />
      </mesh>
      <mesh geometry={nodes.wing_bottom_right.geometry} material={materials.X_Wing_texture} onClick={(e)=>toggleWingRotation(e.object, [0,0,0.2])}>
        <group position={[-11.571, -5.539, -8.455]}>
          <mesh geometry={nodes['X-Wing_fighter006'].geometry} material={materials.X_Wing_texture} onClick={(e)=>{highlight(e.object)}} />
        </group>
        <mesh geometry={nodes.gun_bottom_right.geometry} material={materials.X_Wing_texture} position={[-37.25, -2.696, 16.141]} onClick={(e)=>highlight(e.object)}   />
      </mesh>
      <mesh geometry={nodes.wing_top_left.geometry} material={materials.X_Wing_texture} onClick={(e)=>toggleWingRotation(e.object, [0,0,0.2])} >
        <group position={[11.571, 5.539, -8.455]}>
          <mesh geometry={nodes['X-Wing_fighter008'].geometry} material={materials.X_Wing_texture} onClick={(e)=>highlight(e.object)} />
        </group>
        <mesh geometry={nodes.gun_top_left.geometry} material={materials.X_Wing_texture} position={[37.25, 2.696, 16.141]} onClick={(e)=>highlight(e.object)}/>
      </mesh>
      <mesh geometry={nodes.wing_top_right.geometry} material={materials.X_Wing_texture} onClick={(e)=>toggleWingRotation(e.object, [0,0,-0.2])}>
        <group position={[-11.571, 5.539, -8.455]}>
          <mesh geometry={nodes['X-Wing_fighter007'].geometry} material={materials.X_Wing_texture} onClick={(e)=>highlight(e.object)} />
        </group>
        <mesh geometry={nodes.gun_top_right.geometry} material={materials.X_Wing_texture} position={[-37.25, 2.696, 16.141]} onClick={(e)=>highlight(e.object)}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('models/r3f_xwing2.glb')
