/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 /Users/anthonyaragues/Documents/lab/web3d/public/models/r3f_test.glb -o /Users/anthonyaragues/Documents/lab/web3d/models/r3f_test.js -p 3 -i -s 
Files: /Users/anthonyaragues/Documents/lab/web3d/public/models/r3f_test.glb [183.83KB] > r3f_test-transformed.glb [15.68KB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/r3f_test-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0, 1.417, 0]} scale={1.685} />
    </group>
  )
}

useGLTF.preload('models/r3f_test-transformed.glb')
